all:
	$(MAKE) -C dealer_rep
	$(MAKE) -C dealer_router
	$(MAKE) -C req_rep
	$(MAKE) -C req_router

clean:
	$(MAKE) -C dealer_rep clean
	$(MAKE) -C dealer_router clean
	$(MAKE) -C req_rep clean
	$(MAKE) -C req_router clean

